companies:
- provider: greenhouse
  token: postman
  name: Postman
- provider: greenhouse
  token: groww
  name: Groww
- provider: lever
  token: zeta
  name: Zeta
- provider: lever
  token: meesho
  name: Meesho
- provider: greenhouse
  token: encora10
  name: Encora
- provider: greenhouse
  token: octus
  name: Octus
- provider: greenhouse
  token: forwardnetworks
  name: Forward Networks
- provider: greenhouse
  token: behavox
  name: Behavox
- provider: greenhouse
  token: gr8tech
  name: GR8 Tech
- provider: greenhouse
  token: crashplan
  name: CrashPlan
candidates:
- provider: greenhouse
  token: tide
  name: Tide
- provider: greenhouse
  token: okta
  name: Okta
- provider: greenhouse
  token: bloomreach
  name: Bloomreach
- provider: greenhouse
  token: twilio
  name: Twilio
- provider: greenhouse
  token: prodlyjobs
  name: Prodly
- provider: greenhouse
  token: capco
  name: Capco
- provider: greenhouse
  token: commvault
  name: Commvault
- provider: greenhouse
  token: definian
  name: Definian
- provider: greenhouse
  token: nmi
  name: NMI
- provider: greenhouse
  token: mitratech
  name: Mitratech
- provider: greenhouse
  token: poppulo
  name: Poppulo
- provider: lever
  token: 3pillarglobal
  name: 3Pillar Global
- provider: lever
  token: remofirst
  name: RemoFirst
- provider: ashby
  token: real
  name: Real
- provider: ashby
  token: oscilar
  name: Oscilar
- provider: greenhouse
  token: razorpay
  name: Razorpay
- provider: greenhouse
  token: cred
  name: CRED
- provider: greenhouse
  token: chargebee
  name: Chargebee
- provider: greenhouse
  token: postman
  name: Postman
- provider: greenhouse
  token: groww
  name: Groww
- provider: lever
  token: zeta
  name: Zeta
- provider: lever
  token: meesho
  name: Meesho
- provider: ashby
  token: juspay
  name: Juspay
- provider: greenhouse
  token: encora10
  name: Encora
- provider: greenhouse
  token: octus
  name: Octus
- provider: greenhouse
  token: forwardnetworks
  name: Forward Networks
- provider: greenhouse
  token: behavox
  name: Behavox
- provider: greenhouse
  token: gr8tech
  name: GR8 Tech
- provider: greenhouse
  token: crashplan
  name: CrashPlan
